"""text

Revision ID: d23189c8d8d7
Revises: 
Create Date: 2023-04-14 01:57:24.617065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23189c8d8d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jokes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text_begin', sa.TEXT(), nullable=False),
    sa.Column('text_end', sa.TEXT(), nullable=False),
    sa.Column('language', sa.Enum('RU', 'EN', name='jokelanguages'), nullable=False),
    sa.Column('likes', sa.INTEGER(), nullable=True),
    sa.Column('dislikes', sa.INTEGER(), nullable=True),
    sa.Column('displays', sa.INTEGER(), nullable=True),
    sa.Column('hints_shown', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('language', sa.Enum('RU', 'EN', name='jokelanguages'), nullable=True),
    sa.Column('state', sa.Enum('NOTHING', 'JOKE_IN_PROGRESS', 'FEEDBACK_IN_PROGRESS', name='fsmstate'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('joke_guesses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('joke_id', sa.INTEGER(), nullable=False),
    sa.Column('grade', sa.FLOAT(), nullable=True),
    sa.Column('likes', sa.INTEGER(), nullable=True),
    sa.Column('dislikes', sa.INTEGER(), nullable=True),
    sa.Column('displays', sa.INTEGER(), nullable=True),
    sa.Column('hints_shown', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['joke_id'], ['jokes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('joke_hints',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('joke_id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['joke_id'], ['jokes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('joke_reactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('joke_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('reaction', sa.Enum('LIKE', 'DISLIKE', name='jokereactiontypes'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['joke_id'], ['jokes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('joke_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('joke_id', sa.INTEGER(), nullable=False),
    sa.Column('hints_shown', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['joke_id'], ['jokes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_feedbacks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('joke_guess_reactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('joke_guess_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('reaction', sa.Enum('LIKE', 'DISLIKE', name='jokereactiontypes'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['joke_guess_id'], ['joke_guesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('joke_guess_reactions')
    op.drop_table('user_feedbacks')
    op.drop_table('joke_sessions')
    op.drop_table('joke_reactions')
    op.drop_table('joke_hints')
    op.drop_table('joke_guesses')
    op.drop_table('users')
    op.drop_table('jokes')
    # ### end Alembic commands ###
