package mksoft.sharemoments.entity;
// Generated Apr 9, 2019 2:11:38 AM by Hibernate Tools 4.3.1



/**
 * PhotoPost generated by hbm2java
 */
public class PhotoPost implements java.io.Serializable {


     private Integer id;
     private User user;
     public String src;
     private String text;

    public PhotoPost() {
    }

	
    public PhotoPost(String src) {

        this.src = src;
    }
    public PhotoPost(User user, String src, String text) {
       this.user = user;
       this.src = src;
       this.text = text;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getSrc() {
        return this.src;
    }
    
    public void setSrc(String src) {
        this.src = src;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }

    public String getSid() {
        return "post" + this.getId();
    }


}


