package mksoft.sharemoments.entity;
// Generated Apr 9, 2019 7:52:20 PM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.Id;




/**
 * PhotoPost generated by hbm2java
 */
@Entity
public class PhotoPost  implements java.io.Serializable {

        @Id
     private Integer id;
     private User user;
     private String src;
     private String text;

    public PhotoPost() {
    }

	
    public PhotoPost(User user, String src) {
        this.user = user;
        this.src = src;
    }
    public PhotoPost(User user, String src, String text) {
       this.user = user;
       this.src = src;
       this.text = text;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getSrc() {
        return this.src;
    }
    
    public void setSrc(String src) {
        this.src = src;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }    
    
     @Override
    public String toString() {
        return "post" + id;
    }
       

}


