package mksoft.sharemoments.entity;
// Generated Apr 9, 2019 7:52:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * User generated by hbm2java
 */
@Entity
public class User  implements java.io.Serializable {

       @Id
     private Integer userId;
     private String login;
     private String password;
     private Set photoPosts = new HashSet(0);

    public User() {
    }

	
    public User(String login, String password) {
        this.login = login;
        this.password = password;
    }
    public User(String login, String password, Set photoPosts) {
       this.login = login;
       this.password = password;
       this.photoPosts = photoPosts;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getPhotoPosts() {
        return this.photoPosts;
    }
    
    public void setPhotoPosts(Set photoPosts) {
        this.photoPosts = photoPosts;
    }




}


